In [1]:
def img2vector(filename):
    mylist = []
    fr = open(filename)
    height=32;
    width=32;
    for i in range(height):
        lineStr=fr.readline()
        #print len(mylist)
        for j in range(width):
            mylist.append(int(lineStr[j]))
    #mat = numpy.array(mylist)
    return mylist
import os
import numpy as np
os.chdir('/home/jsl/Code/git/else/machinelearninginaction/Ch02/trainingDigits')
dir=os.getcwd()
trainingFileList=os.listdir(dir)
filename=trainingFileList[0]
print filename

0_114.txt


#벡터를 합하는 문제

In [17]:
data=img2vector(filename)
print len(data)
a=np.array(range(0,10))
b=np.array(range(10,20))
ab=np.vstack([a,b])
print ab.shape
c=np.array(range(30,40))
abc=np.vstack([ab,c])
print abc

1024
(2, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39]]


In [3]:
m=len(trainingFileList)
print m
trainingMat=np.zeros((m,1024))
for i in range(m):
    filename=trainingFileList[i]
    trainingMat[i,:]=img2vector(filename)
print trainingMat.shape

1934
(1934, 1024)


In [14]:
print trainingMat[:5,:15]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]


In [15]:
!cat 0_114.txt